#!/usr/bin/env python3
from __future__ import annotations

import importlib.util
import json
import tempfile
import unittest
from pathlib import Path
from types import SimpleNamespace
from unittest.mock import patch

TESTS_DIR = Path(__file__).resolve().parent
SKILL_DIR = TESTS_DIR.parent
SCRIPT_PATH = SKILL_DIR / "scripts" / "youtube_to_xiaohongshu_post.py"
STRUCTURED_SCHEMA_PATH = SKILL_DIR / "scripts" / "structured_summary.schema.json"
POST_SCHEMA_PATH = SKILL_DIR / "scripts" / "xiaohongshu_post.schema.json"

spec = importlib.util.spec_from_file_location("youtube_to_xiaohongshu_post", SCRIPT_PATH)
module = importlib.util.module_from_spec(spec)
assert spec and spec.loader
spec.loader.exec_module(module)


class XiaohongshuPostTests(unittest.TestCase):
    def test_skill_docs_require_explicit_xiaohongshu_request(self) -> None:
        skill_text = (SKILL_DIR / "SKILL.md").read_text(encoding="utf-8")

        self.assertIn("scripts/youtube_to_xiaohongshu_post.py", skill_text)
        self.assertIn("only when the user explicitly asks for Xiaohongshu", skill_text)
        self.assertIn("小红书", skill_text)

    def test_fetch_wrapper_does_not_forward_a_caption_strategy(self) -> None:
        args = SimpleNamespace(video="abc123def45", langs="en")
        payload = {"schema_version": "caption.v2"}
        with tempfile.TemporaryDirectory() as temp_name:
            output = Path(temp_name) / "caption.json"

            def fake_run(command, **kwargs):
                del kwargs
                output.write_text(json.dumps(payload), encoding="utf-8")
                self.assertNotIn("--strategy", command)
                self.assertNotIn("--providers", command)
                return SimpleNamespace(returncode=0, stdout="", stderr="")

            with patch.object(module.subprocess, "run", side_effect=fake_run):
                result = module.run_fetch_step(args, output)
        self.assertEqual(payload, result)

    def test_cleaned_transcript_artifact_keeps_metadata_text_chunks_and_notes(self) -> None:
        caption = {
            "schema_version": "caption.v2",
            "video": {
                "video_id": "abc123def45",
                "source_url": "https://www.youtube.com/watch?v=abc123def45",
                "title": "How builders ship faster",
            },
            "selected_result": {
                "chapters": [{"title": "Intro", "timestamp": "00:00"}],
                "text": " hello  \n\nworld ",
                "raw_metadata": {
                    "channel": "Builder Channel",
                    "description": "A practical video about shipping.",
                },
            },
            "chunks": [{"timestamp": "00:00", "text": "hello world"}],
            "notes": ["Selected caption is generated by YouTube; review important claims carefully."],
        }

        cleaned = module.build_cleaned_transcript_artifact(caption)

        self.assertEqual("How builders ship faster", cleaned["video_title"])
        self.assertEqual("https://www.youtube.com/watch?v=abc123def45", cleaned["video_url"])
        self.assertEqual("Builder Channel", cleaned["channel_name"])
        self.assertEqual("A practical video about shipping.", cleaned["video_description"])
        self.assertEqual([{"title": "Intro", "timestamp": "00:00"}], cleaned["chapters"])
        self.assertEqual("hello\nworld", cleaned["transcript"])
        self.assertEqual([{"timestamp": "00:00", "text": "hello world"}], cleaned["chunks"])
        self.assertIn("generated by YouTube", cleaned["notes"][0])

    def test_final_rewrite_prompt_uses_structured_summary_not_full_transcript(self) -> None:
        prompt = module.build_xiaohongshu_prompt(Path("/tmp/structured_summary.json"))

        self.assertIn("structured_summary", prompt)
        self.assertIn("小红书", prompt)
        self.assertIn("不得新增结构化摘要里没有的信息", prompt)
        self.assertIn("可直接发布", prompt)
        self.assertIn("客观", prompt)
        self.assertIn("这不是个人观后感", prompt)
        self.assertIn("不使用“我”", prompt)
        self.assertIn("以下内容基于 YouTube 视频", prompt)
        self.assertIn("来源句 + 4 个小标题段 + 结尾句", prompt)
        self.assertIn("70-110", prompt)
        self.assertIn("不要频繁写", prompt)
        self.assertIn("不要生成这种风格", prompt)
        for field_name in ("title_groups", "cover_lines", "body", "tags", "fact_check"):
            self.assertIn(field_name, prompt)
        for field_name in ("claim", "source_type", "source_detail"):
            self.assertIn(field_name, prompt)
        for title_type in ("痛点型", "反常识型", "人群型", "观点型"):
            self.assertIn(title_type, prompt)
        self.assertNotIn("字幕全文", prompt)
        self.assertNotIn("完整字幕", prompt)

    def test_render_markdown_post_requires_objective_source_note(self) -> None:
        payload = {
            "title_groups": {
                "pain_point": ["标题一", "标题二"],
                "counterintuitive": ["标题三", "标题四"],
                "audience": ["标题五", "标题六"],
                "viewpoint": ["标题七", "标题八"],
            },
            "cover_lines": ["封面一", "封面二", "封面三", "封面四", "封面五"],
            "body": "正" * 600,
            "tags": ["标签一", "标签二", "标签三", "标签四", "标签五", "标签六", "标签七", "标签八"],
            "fact_check": [
                {"claim": "信息", "source_type": "结构化摘要", "source_detail": "摘要"}
            ] * 5,
        }

        with self.assertRaisesRegex(module.UserError, "source"):
            module.render_markdown_post(payload)

    def test_render_markdown_post_rejects_first_person_body(self) -> None:
        payload = {
            "title_groups": {
                "pain_point": ["标题一", "标题二"],
                "counterintuitive": ["标题三", "标题四"],
                "audience": ["标题五", "标题六"],
                "viewpoint": ["标题七", "标题八"],
            },
            "cover_lines": ["封面一", "封面二", "封面三", "封面四", "封面五"],
            "body": "以下内容基于 YouTube 视频《测试标题》的字幕整理与翻译，不是逐字稿。" + "我" + "正" * 600,
            "tags": ["标签一", "标签二", "标签三", "标签四", "标签五", "标签六", "标签七", "标签八"],
            "fact_check": [
                {"claim": "信息", "source_type": "结构化摘要", "source_detail": "摘要"}
            ] * 5,
        }

        with self.assertRaisesRegex(module.UserError, "first-person"):
            module.render_markdown_post(payload)

    def test_render_markdown_post_reports_missing_required_field(self) -> None:
        with self.assertRaisesRegex(module.UserError, "cover_lines"):
            module.render_markdown_post(
                {
                    "title_groups": {
                        "pain_point": ["标题一", "标题二"],
                        "counterintuitive": ["标题三", "标题四"],
                        "audience": ["标题五", "标题六"],
                        "viewpoint": ["标题七", "标题八"],
                    },
                    "body": "正" * 600,
                    "tags": ["标签"],
                    "fact_check": [],
                }
            )

    def test_render_markdown_post_reports_invalid_fact_check_item(self) -> None:
        payload = {
            "title_groups": {
                "pain_point": ["标题一", "标题二"],
                "counterintuitive": ["标题三", "标题四"],
                "audience": ["标题五", "标题六"],
                "viewpoint": ["标题七", "标题八"],
            },
            "cover_lines": ["封面一", "封面二", "封面三", "封面四", "封面五"],
            "body": "以下内容基于 YouTube 视频《测试标题》的字幕整理与翻译，不是逐字稿。" + "正" * 600,
            "tags": ["标签一", "标签二", "标签三", "标签四", "标签五", "标签六", "标签七", "标签八"],
            "fact_check": ["字符串不是事实核对对象"] * 5,
        }

        with self.assertRaisesRegex(module.UserError, "fact_check"):
            module.render_markdown_post(payload)

    def test_render_markdown_post_reports_body_outside_required_range(self) -> None:
        payload = {
            "title_groups": {
                "pain_point": ["标题一", "标题二"],
                "counterintuitive": ["标题三", "标题四"],
                "audience": ["标题五", "标题六"],
                "viewpoint": ["标题七", "标题八"],
            },
            "cover_lines": ["封面一", "封面二", "封面三", "封面四", "封面五"],
            "body": "以下内容基于 YouTube 视频《测试标题》的字幕整理与翻译，不是逐字稿。" + "正" * 901,
            "tags": ["标签一", "标签二", "标签三", "标签四", "标签五", "标签六", "标签七", "标签八"],
            "fact_check": [
                {"claim": "信息", "source_type": "结构化摘要", "source_detail": "摘要"}
            ] * 5,
        }

        with self.assertRaisesRegex(module.UserError, "body"):
            module.render_markdown_post(payload)

    def test_chunking_threshold_is_explicit(self) -> None:
        self.assertFalse(module.should_chunk_transcript("x" * 20_000, 20_000))
        self.assertTrue(module.should_chunk_transcript("x" * 20_001, 20_000))

    def test_ensure_codex_cli_skips_broken_path_candidate(self) -> None:
        with tempfile.TemporaryDirectory() as temp_name:
            temp_dir = Path(temp_name)
            broken = temp_dir / "broken-codex"
            fallback = temp_dir / "fallback-codex"
            broken.write_text("#!/bin/sh\nexit 1\n", encoding="utf-8")
            fallback.write_text("#!/bin/sh\necho codex-cli test\nexit 0\n", encoding="utf-8")
            broken.chmod(0o755)
            fallback.chmod(0o755)

            with patch.object(module.shutil, "which", return_value=str(broken)):
                with patch.object(module, "BUNDLED_CODEX_CANDIDATES", [fallback]):
                    self.assertEqual(str(fallback), module.ensure_codex_cli())

    def test_group_transcript_chunks_combines_nearby_chunks(self) -> None:
        chunks = [
            {"start": 0.0, "end": 90.0, "timestamp": "00:00", "text": "first"},
            {"start": 90.0, "end": 180.0, "timestamp": "01:30", "text": "second"},
            {"start": 700.0, "end": 790.0, "timestamp": "11:40", "text": "third"},
        ]

        groups = module.group_transcript_chunks(chunks, max_seconds=600.0, max_chars=20_000)

        self.assertEqual(2, len(groups))
        self.assertEqual("00:00", groups[0]["timestamp"])
        self.assertEqual(0.0, groups[0]["start"])
        self.assertEqual(180.0, groups[0]["end"])
        self.assertEqual(2, groups[0]["chunk_count"])
        self.assertEqual("first\nsecond", groups[0]["text"])
        self.assertEqual("third", groups[1]["text"])

    def test_merge_chunk_summaries_batches_large_inputs(self) -> None:
        summary = {
            "one_sentence_summary": "一句话总结",
            "main_question": "主要问题",
            "core_viewpoints": [{"point": "观点", "evidence_or_examples": ["例子"]}],
            "important_concepts": ["概念"],
            "data_facts_quotes": ["事实"],
            "outline": ["大纲"],
            "takeaways": ["要点一", "要点二", "要点三"],
            "insufficient_evidence": [],
        }
        chunk_summaries = [
            {**summary, "one_sentence_summary": f"分段 {index}"}
            for index in range(8)
        ]

        with tempfile.TemporaryDirectory() as temp_name:
            temp_dir = Path(temp_name)
            prompts: list[str] = []

            def fake_codex_step(**kwargs):
                prompts.append(kwargs["prompt"])
                return {**summary, "one_sentence_summary": f"合并 {len(prompts)}"}

            with patch.object(module, "run_codex_json_step", side_effect=fake_codex_step):
                result = module.merge_chunk_summaries(
                    codex_path="/usr/bin/codex",
                    chunk_summaries=chunk_summaries,
                    temp_dir=temp_dir,
                    model=None,
                    merge_batch_size=3,
                    reasoning_effort=None,
                )

        self.assertEqual("合并 4", result["one_sentence_summary"])
        self.assertEqual(4, len(prompts))
        self.assertTrue(all("分段结构化摘要 JSON" in prompt for prompt in prompts))

    def test_default_merge_batch_size_keeps_merge_prompts_small(self) -> None:
        with patch.object(module.sys, "argv", ["youtube_to_xiaohongshu_post.py", "abc123def45"]):
            args = module.parse_args()

        self.assertEqual(2, args.merge_batch_size)

    def test_codex_json_step_overrides_reasoning_effort_by_default(self) -> None:
        with tempfile.TemporaryDirectory() as temp_name:
            temp_dir = Path(temp_name)
            readable_path = temp_dir / "input.json"
            schema_path = temp_dir / "schema.json"
            readable_path.write_text("{}", encoding="utf-8")
            schema_path.write_text("{}", encoding="utf-8")
            commands: list[list[str]] = []

            def fake_run(command, **kwargs):
                commands.append(command)
                output_path = Path(command[command.index("-o") + 1])
                output_path.write_text('{"ok": true}', encoding="utf-8")

                class Completed:
                    returncode = 0
                    stdout = ""
                    stderr = ""

                return Completed()

            with patch.object(module.subprocess, "run", side_effect=fake_run):
                module.run_codex_json_step(
                    codex_path="/usr/bin/codex",
                    prompt="prompt",
                    schema_path=schema_path,
                    readable_paths=[readable_path],
                    model=None,
                    reasoning_effort="low",
                )

        command = commands[0]
        self.assertIn("-c", command)
        self.assertIn('model_reasoning_effort="low"', command)

    def test_long_transcript_generation_uses_chunk_then_merge_flow(self) -> None:
        cleaned = {
            "video_title": "Long video",
            "video_url": "https://www.youtube.com/watch?v=abc123def45",
            "channel_name": None,
            "video_description": None,
            "transcript": "x" * 10,
            "chunks": [
                {"start": 0.0, "end": 90.0, "timestamp": "00:00", "text": "first chunk"},
                {"start": 700.0, "end": 790.0, "timestamp": "11:40", "text": "second chunk"},
            ],
            "notes": [],
        }
        summary = {
            "one_sentence_summary": "一句话总结",
            "main_question": "主要问题",
            "core_viewpoints": [{"point": "观点", "evidence_or_examples": ["例子"]}],
            "important_concepts": ["概念"],
            "data_facts_quotes": ["事实"],
            "outline": ["大纲"],
            "takeaways": ["要点一", "要点二", "要点三"],
            "insufficient_evidence": [],
        }

        with tempfile.TemporaryDirectory() as temp_name:
            temp_dir = Path(temp_name)
            cleaned_path = temp_dir / "cleaned.json"
            chunk_summaries_path = temp_dir / "chunk_summaries.json"
            cleaned_path.write_text(json.dumps(cleaned, ensure_ascii=False), encoding="utf-8")
            prompts: list[str] = []

            def fake_codex_step(**kwargs):
                prompts.append(kwargs["prompt"])
                return summary

            with patch.object(module, "run_codex_json_step", side_effect=fake_codex_step):
                result = module.generate_structured_summary(
                    codex_path="/usr/bin/codex",
                    cleaned=cleaned,
                    cleaned_path=cleaned_path,
                    threshold=3,
                    model=None,
                    chunk_summaries_output=str(chunk_summaries_path),
                    chunk_group_seconds=600.0,
                    chunk_group_max_chars=20_000,
                    merge_batch_size=5,
                    reasoning_effort=None,
                )
            saved_chunks = json.loads(chunk_summaries_path.read_text(encoding="utf-8"))

        self.assertEqual(summary, result)
        self.assertEqual(3, len(prompts))
        self.assertIn("单段字幕 JSON", prompts[0])
        self.assertIn("单段字幕 JSON", prompts[1])
        self.assertIn("分段结构化摘要 JSON", prompts[2])
        self.assertEqual(2, len(saved_chunks))

    def test_render_markdown_post_outputs_required_sections(self) -> None:
        payload = {
            "title_groups": {
                "pain_point": ["痛点一", "痛点二"],
                "counterintuitive": ["反常识一", "反常识二"],
                "audience": ["人群一", "人群二"],
                "viewpoint": ["观点一", "观点二"],
            },
            "cover_lines": ["封面一", "封面二", "封面三", "封面四", "封面五"],
            "body": "以下内容基于 YouTube 视频《测试标题》的字幕整理与翻译，不是逐字稿。" + "正" * 600,
            "tags": ["学习", "效率", "视频笔记", "知识", "方法", "总结", "内容", "小红书"],
            "fact_check": [
                {"claim": "信息一", "source_type": "字幕", "source_detail": "00:01"},
                {"claim": "信息二", "source_type": "标题", "source_detail": "视频标题"},
                {"claim": "信息三", "source_type": "章节", "source_detail": "Intro"},
                {"claim": "信息四", "source_type": "描述", "source_detail": "视频描述"},
                {"claim": "信息五", "source_type": "字幕", "source_detail": "00:20"},
            ],
        }

        rendered = module.render_markdown_post(payload)

        self.assertIn("【标题】", rendered)
        self.assertIn("痛点型", rendered)
        self.assertIn("反常识型", rendered)
        self.assertIn("人群型", rendered)
        self.assertIn("观点型", rendered)
        self.assertIn("【封面文案】", rendered)
        self.assertIn("【正文】", rendered)
        self.assertIn("【标签】", rendered)
        self.assertNotIn("【事实检查】", rendered)
        self.assertNotIn("| 信息点 | 来源类型 | 来源说明 |", rendered)
        self.assertIn("#视频笔记", rendered)

    def test_schemas_encode_required_output_counts(self) -> None:
        structured_schema = json.loads(STRUCTURED_SCHEMA_PATH.read_text(encoding="utf-8"))
        post_schema = json.loads(POST_SCHEMA_PATH.read_text(encoding="utf-8"))

        self.assertIn("one_sentence_summary", structured_schema["required"])
        self.assertEqual(3, structured_schema["properties"]["takeaways"]["minItems"])
        self.assertEqual(3, structured_schema["properties"]["takeaways"]["maxItems"])
        self.assertEqual(5, structured_schema["properties"]["core_viewpoints"]["maxItems"])
        self.assertEqual(220, structured_schema["properties"]["one_sentence_summary"]["maxLength"])
        self.assertEqual(260, structured_schema["properties"]["main_question"]["maxLength"])
        viewpoint_schema = structured_schema["properties"]["core_viewpoints"]["items"]
        self.assertEqual(220, viewpoint_schema["properties"]["point"]["maxLength"])
        self.assertEqual(4, viewpoint_schema["properties"]["evidence_or_examples"]["maxItems"])
        self.assertEqual(12, structured_schema["properties"]["important_concepts"]["maxItems"])
        self.assertEqual(12, structured_schema["properties"]["data_facts_quotes"]["maxItems"])
        self.assertEqual(12, structured_schema["properties"]["outline"]["maxItems"])
        self.assertEqual(8, structured_schema["properties"]["insufficient_evidence"]["maxItems"])

        title_groups = post_schema["properties"]["title_groups"]
        self.assertEqual(
            ["pain_point", "counterintuitive", "audience", "viewpoint"],
            title_groups["required"],
        )
        for group_name in title_groups["required"]:
            self.assertEqual(2, title_groups["properties"][group_name]["minItems"])
            self.assertEqual(2, title_groups["properties"][group_name]["maxItems"])
            self.assertEqual(24, title_groups["properties"][group_name]["items"]["maxLength"])
        self.assertEqual(5, post_schema["properties"]["cover_lines"]["minItems"])
        self.assertEqual(5, post_schema["properties"]["cover_lines"]["maxItems"])
        self.assertEqual(600, post_schema["properties"]["body"]["minLength"])
        self.assertEqual(900, post_schema["properties"]["body"]["maxLength"])
        self.assertEqual(8, post_schema["properties"]["tags"]["minItems"])
        self.assertEqual(12, post_schema["properties"]["tags"]["maxItems"])
        self.assertEqual(5, post_schema["properties"]["fact_check"]["minItems"])
        self.assertEqual(8, post_schema["properties"]["fact_check"]["maxItems"])


if __name__ == "__main__":
    unittest.main()
